#!/usr/bin/env python3
"""The voice script: every line Riff and Tango speak, by character and by where
in the game it is heard, with each line's ID (the name its recording is saved
under). Rebuild it whenever the words change:

    python tools/voice-script.py

It reads content/dialogue.js (who says which line, and when) and
lang/en-US.js (the words), and writes docs/voice-script.md.
"""
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
LANG = os.path.join(ROOT, 'lang', 'en-US.js')
DIALOGUE = os.path.join(ROOT, 'content', 'dialogue.js')
OUT = os.path.join(ROOT, 'docs', 'voice-script.md')

LANG_ENTRY = re.compile(r"""^\s*'([^']+)'\s*:\s*('(?:[^'\\]|\\.)*'|"(?:[^"\\]|\\.)*")\s*,""", re.MULTILINE)
LINE = re.compile(r"""\{\s*on:\s*'([^']+)',\s*speaker:\s*'(\w+)',\s*text:\s*'([^']+)'""")
VARIABLE = re.compile(r"\{(\w+)\}")

# Where each event is heard, by the start of its name. First match wins.
PLACES = [
    ('beat.jam.', 'The warm-up jam'),
    ('beat.delay', 'The warm-up jam'),
    ('beat.songs.', 'Choosing a song'),
    ('beat.rules', 'Reading takes: the rules, waiting, the verdict'),
    ('beat.take.', 'Reading takes: the rules, waiting, the verdict'),
    ('beat.retake', 'Reading takes: the rules, waiting, the verdict'),
    ('beat.reveal', 'Reading takes: the rules, waiting, the verdict'),
    ('beat.musician.', 'Each musician\'s steps'),
    ('beat.step.', 'Each musician\'s steps'),
    ('beat.eighths.', 'Each musician\'s steps'),
    ('beat.quavers.', 'Each musician\'s steps'),
    ('beat.studio', 'The studio'),
    ('beat.playback', 'The studio'),
    ('beat.picker.', 'Choosing a part'),
    ('beat.part.', 'Choosing a part'),
    ('beat.permit', 'My band and the Learner\'s Permit'),
    ('beat.band', 'My band and the Learner\'s Permit'),
    ('beat.share', 'My band and the Learner\'s Permit'),
    ('beat.', 'Beat Smash, other'),
    ('value.', 'Value Smash'),
]

# The direction for each voice, Rob's own words where he has given them.
VOICES = {
    'tango': ('Tango', 'the drummer, an orange cat with a red mane and a blue vest. She handles '
              'rhythm. Bright and warm, encouraging, never hyper: Rob\'s classes found the old '
              'high, quick voice annoying (2026-10-08). A drummer counting a band in: steady, '
              'on the beat, a smile in it.'),
    'riff': ('Riff', 'the jazz Scottie dog in a red beret and green vest. Rob: hip and cool, a '
             'New York jazz man who knows all the secrets of memorising and of making beautiful '
             'music and melody. Relaxed, unhurried, warm; he calls people "cat".'),
}


def unquote(literal):
    body = literal[1:-1]
    return re.sub(r"\\(.)", r"\1", body)


def place(event):
    for prefix, name in PLACES:
        if event.startswith(prefix):
            return name
    return 'Other'


def main():
    words = {m.group(1): unquote(m.group(2)) for m in LANG_ENTRY.finditer(open(LANG, encoding='utf-8').read())}
    seen = set()
    lines = []
    for m in LINE.finditer(open(DIALOGUE, encoding='utf-8').read()):
        event, speaker, text_id = m.groups()
        if (speaker, text_id) in seen or speaker not in VOICES:
            continue
        seen.add((speaker, text_id))
        lines.append((speaker, place(event), event, text_id, words.get(text_id, '(missing: ' + text_id + ')')))

    out = ['# The voice script: Riff and Tango', '',
           'Every line the two characters speak, generated from the game\'s own files.',
           '**Do not edit this file**: change the words in `lang/en-US.js`, then run',
           '`python tools/voice-script.py` to rebuild it.', '',
           '## How to record them', '',
           '1. **Choose a voice for each character.** The easiest place to audition is the',
           '   [ElevenLabs Voice Library](https://elevenlabs.io/voice-library) (filter by accent,',
           '   age and style), or its Voice Design, which makes a voice from a description.',
           '   Commercial use needs a paid plan. A real voice actor reading this script works too.',
           '2. **Record each line as its own file, named by its ID**: `beat.line.copy.mp3`.',
           '3. **Put the files in `audio/voice/`** and list them in `content/audio.js` by the',
           '   same ID. The game plays a recording in place of the browser\'s voice whenever one',
           '   is listed (`KR.speak` in `text.js`); nothing else changes.', '',
           '**Lines with a part in {braces}** are filled in by the game as it is played: `{take}`',
           'is "Take two!", "Take three!"..., `{n}`, `{score}` and the like are numbers or names.',
           'A recording can\'t change, so these lines are marked below. For now, record them',
           'without the braced part, and the game will need a small change to play the braced',
           'part after them; or leave them to the browser\'s voice.', '']
    for speaker, (name, direction) in VOICES.items():
        mine = [l for l in lines if l[0] == speaker]
        out += ['## ' + name + ' (' + str(len(mine)) + ' lines)', '', '**Voice:** ' + direction, '']
        for heading in dict.fromkeys([p for _, p in PLACES] + ['Other']):
            group = [l for l in mine if l[1] == heading]
            if not group:
                continue
            out += ['### ' + heading, '', '| ID (the file name) | Line | Heard when |', '|---|---|---|']
            for _, _, event, text_id, said in group:
                mark = ' **(filled in: ' + ', '.join('{' + v + '}' for v in VARIABLE.findall(said)) + ')**' if VARIABLE.search(said) else ''
                out.append('| `' + text_id + '` | ' + said.replace('|', '\\|') + mark + ' | `' + event + '` |')
            out.append('')
    open(OUT, 'w', encoding='utf-8').write('\n'.join(out))
    print('voice script: %d lines (%s) -> %s' % (len(lines), ', '.join(
        '%s %d' % (VOICES[s][0], sum(1 for l in lines if l[0] == s)) for s in VOICES), os.path.relpath(OUT, ROOT)))


if __name__ == '__main__':
    main()
